name: First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
     - name: Check Node Version
  run: node -v

- name: Check NPM Version
  run: npm -v

- name: Install Dependencies
  run: npm ci

- name: List Project Files
  run: ls -la